---
- name: Deploy Docker Containers
  hosts: containers
  become: yes  # Run tasks as root
  tasks:

    - name: Install required system packages
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
          - ca-certificates
          - curl
        state: present

    - name: Add Docker repository
      command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: Install Docker Engine
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull the Docker image from Docker Hub
      command: docker pull shahdmohammed/weather-app:latest

    - name: Remove old running container (if exists)
      command: docker rm -f weather-app || true

    - name: Run the Docker container
      command: docker run -d --name weather-app -p 5000:5000 shahdmohammed/weather-app:latest
